apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardvalidator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cardvalidator
  template:
    metadata:
      labels:
        app: cardvalidator
    spec:
      containers:
      - name: creditcardvalidator
        image: {image}:{tag}
        ports:
        - containerPort: 80
